### ISSUE TITLE
Would you be interested in porting this to the new Turnigy Evolution

### ISSUE THREAD

**Issue by andymac4182** [fishpepper/OpenGround#1] opened 2016-10-28 20:30 UTC
Hi,

Have you had a look at whether it is possible to port this to the new Turnigy Evolution? 

https://hobbyking.com/en_us/fpv-racer-radio-mode-2-white.html

https://www.youtube.com/watch?v=ZMHVIhZzSMI

Cheers,
Andrew

**Comment by fishpepper** [comment] 2016-10-29 08:41
Should be no big deal. If someone sends me a tgy evolution i will have a look and if it uses the same hardware as the i6s i will port my code. It should be enough to have it 2-3 weeks for the initial porting. I am located in germany.

**Comment by maymayday90** [comment] 2016-10-29 21:40
Yes, would also be very interested in this. As far as I know, hardware is almost identical, though I'll be getting my Evo soon and can double check.

Is there a PPM stream available either with stock firmware or your firmware? Thinking external modules. From your pinout documentation it seems like the current transceiver chip is fed data (serial?) instead of PPM.

Have you looked at the opentx or er9x repositories at all? Lots of good stuff in those as well. Could save you lots of work instead of writing from the ground up for some of these.

**Comment by fishpepper** [comment] 2016-10-30 07:20
I know and use OpenTX on my main tx. The reason for writing openground from scratch is that opentx has way to many features i do not need at all on my quadcopters. I want something plain and simple. Not more ;)
The stock and CC2500 modules are both fed via SPI. Right now i do not plan adding ppm stream output as this adds unnecessary delays and i prefer the clean and direct connection to the module. The stock firmware could have a ppm output on the trainer port?!

**Comment by maymayday90** [comment] 2016-10-30 12:14
I will agree on way too many features. More of a pick and choose as needed and pull across to OpenGround. But I'm not doing the hardwork, you are. My coding is not even close to being able to write stuff for this.

Reason for PPM out is for external modules. Frsky module (though you have that already with the CC2500 module, but was thinking an XJT module or something), DSMX module, and most importantly, my TBS Crossfire. :D

Would a PPM stream overload the CPU that badly? I know it's not the best STM processor out there, but would think it could handle it? Maybe have it so you could enable or disable it, check box style.

But just wishes from a guy that can't do it himself. ;)

**Comment by fishpepper** [comment] 2016-10-30 12:17
PPM output e.g. on the trainer port should be no big deal. It can be generated by a hardware timer.

**Comment by maymayday90** [comment] 2016-10-30 22:54
No trainer port on the Evolution. Would have to be hacked probably.

**Comment by maymayday90** [comment] 2016-11-11 05:04
![2016-11-10 20 50 33](https://cloud.githubusercontent.com/assets/11403133/20204923/f209d980-a788-11e6-9650-ecd55bb34c70.jpg)
![2016-11-10 20 50 58](https://cloud.githubusercontent.com/assets/11403133/20204924/f20d259a-a788-11e6-9ab2-f382aeec643d.jpg)

I'm sure you probably have pics already of this, but here's the internals of the Evolution. Seems almost identical to the i6s. There is no trainer port though, do you know where to get PPM out for an external module? Can it be pulled from one the lines going to the internal transceiver module?

Thanks!

**Comment by metalnow** [comment] 2016-11-15 03:37
Is it possible rewrite the driver of stock RF module for TGY-EVO?

**Comment by andymac4182** [comment] 2016-11-15 06:12
I might be wrong but I that it wouldn't help due to the different modules doing different modulation. It would be good to see someone add support for FlySky as this is a great radio just not awesome receivers or firmware.

**Comment by andymac4182** [comment] 2016-11-16 06:47
@fishpepper I have sent you an email about how to send you the money for this if you are still interested 👍

**Comment by fishpepper** [comment] 2016-11-16 08:14
The stock module uses a different chipset as FrSky. I have never used it and i do not know the flysky protocol. But soemone who does could easily add support for that in the code. Then one would have to use the flysky receivers as well.

@andymac4182: i did not get any email from you. Where did you send it to? Try fishpepper <AT> gmail.com Thanks :)

**Comment by andymac4182** [comment] 2016-11-16 08:39
@fishpepper I have emailed that address now :)

**Comment by cj1324** [comment] 2016-11-17 02:08
@fishpepper 

Does this project help you?
https://github.com/tipouic/DIY-Multiprotocol-TX-Module/tree/flysky_afhds2a

**Comment by add1ct3dd** [comment] 2016-11-29 13:12
Subbed

**Comment by totterfree** [comment] 2016-12-07 20:51
Also curious as to how this turns out. I'd love to be able to Tiny Whoop with the Evolution

**Comment by jacobbloy** [comment] 2016-12-17 04:35
https://www.rcgroups.com/forums/showthread.php?t=2566271&page=18#post35433517

Adding a external module to the i6s might work for the evolution. The trainer port could be there just not active

**Comment by maymayday90** [comment] 2016-12-17 04:56
Hmm yes, I like that. Can't see what's on that trainer pcb though, might be a conversion chip or something.

**Comment by jacobbloy** [comment] 2016-12-17 05:38
who has a i6s that can have a look? mine is in the mail

**Comment by Tesla99** [comment] 2016-12-17 13:46
I have the i6s. What do u need?

**Comment by jacobbloy** [comment] 2016-12-17 14:41
You will need to pop it open then take a picture on the small pcb that the trainer port is soldered to. Need a pic of both sides so we can see if there is an ic or resistors ect. If we can replicate this board then we can try and add it into the evolution. If looks like the evolution has the plug header for it.

**Comment by jacobbloy** [comment] 2016-12-17 14:46
This pcb on the other side I guess
https://static.rcgroups.net/forums/attachments/1/3/6/1/8/5/a9237516-44-image.jpg

**Comment by jacobbloy** [comment] 2016-12-17 15:05
Then if there are no ic's ect on that little pcb, just above the header for the little pcb s wire harness, there is a pad labeled ppm out, we need to trace this back to the mcu  and find out what pin it is using. If we can locate that we can see if the evolution has ppm on the pin also

**Comment by Tesla99** [comment] 2016-12-18 04:52
Ok I'll click some pics and post them tomorrow. Lots of work today...

**Comment by maymayday90** [comment] 2016-12-19 07:47
I have never had my fingers crossed this hard hoping it can be traced back on the Evolution...

**Comment by maymayday90** [comment] 2016-12-19 08:36
![capture](https://cloud.githubusercontent.com/assets/11403133/21305909/07eaa97e-c583-11e6-99d6-c9d089857095.JPG)

Looks like the PPM out is here, if there's no IC or anything on the separate PCB. Continuity check it to every pin on the ARM processor! And hope it's possible.

**Comment by francescromai** [comment] 2016-12-20 11:01
Hello everybody! I'm new in that kind of projects, but it could be awesome if we can use the Evolution radio with frsky receivers!
Is there  any chance?
Cheers

**Comment by jacobbloy** [comment] 2016-12-20 12:02
We are looking into it.

**Comment by andymac4182** [comment] 2016-12-20 22:12
@francescromai Yes it is possible. It is just when someone or @fishpepper has time to port the code.

**Comment by jacobbloy** [comment] 2016-12-22 06:38
it seems like the ppm signal on the i6s is coming from the PD5 pin on the stm32f07 chip with a 200ohm resistor in line. there is no second ic on the trainer port pcb as you can see on the pics attached. is some one has the turnigy evolution a 200ohm resistor and a Oscilloscope you could check is there is actually in fact a ppm signal that i accessible on the evolution.
you will need to connect it up to actual put it in trainer mode i think.
![img_9496](https://cloud.githubusercontent.com/assets/7373557/21417266/3b5fb55e-c869-11e6-8cd2-052e3d4e06fb.JPG)
![img_9495](https://cloud.githubusercontent.com/assets/7373557/21417267/3bac2a56-c869-11e6-87c7-d250e13aa75f.JPG)
![img_9494](https://cloud.githubusercontent.com/assets/7373557/21417269/3c1a1c14-c869-11e6-929c-e2e65585b476.JPG)

**Comment by VR-69** [comment] 2017-01-11 12:36
Maymayday90 Can I connect the ppm out to my crossfire?

**Comment by maymayday90** [comment] 2017-01-11 23:26
Haven't checked this yet. Will try in the next day or two.

**Comment by VR-69** [comment] 2017-01-12 02:27
Ok perfect let me know :)

**Comment by kevinlynn** [comment] 2017-01-12 05:54
Sent you an email about helping with the a7105 chip and getting afhds + afhds 2a out of an i6s / evo

Like most here I prefer frsky but there are so many toy drones that use the older flysky protocol(afhds) If afhds could be added to the evolution then you could use it to control many micro drones from Banggood. Since there's some code already available from the deviation folk and also the multi protocol module it seems like this should be easier than figuring out the protocol the hard way.

Thanks

**Comment by DaveP2017** [comment] 2017-01-16 22:51
Hi All

Well I've digged and I've dug, I've poked and I've prodded just about everything on the Evolution pcb and came up with zilch in the quest for anything resembling a ppm signal....

Which is probably why no one has posted their failure after all this time... I however have no pride so don't mind admitting defeat.

So an rx with ppm out connected directly to a 4 in 1 multi module looks the easy fudge at this time

https://www.youtube.com/watch?v=ez0ia-UhHdM

**Comment by jacobbloy** [comment] 2017-01-16 22:59
So you tried the PD5 pin on the mcu? I'm getting the evolution in a couple of days but I feel like it is turned off in the firmware maybe the next thing is trying to get the i6s firmware loaded on the evolution.

**Comment by andymac4182** [comment] 2017-01-16 23:00
@jacobbloy The pin outs aren't identical between the two controllers. @fishpepper tested OpenGround and its similar but the ADC set up isn't the same.

**Comment by jacobbloy** [comment] 2017-01-16 23:03
That's a bummer. But was worth a try. I guess it will take some more time. But I feel we will eventually have an open firmware for this transmitter that can have an external module.

**Comment by DaveP2017** [comment] 2017-01-16 23:11
> So you tried the PD5 pin on the mcu? 

Yes...  pin 86 and also the other 99 as well, lol

**Comment by andymac4182** [comment] 2017-01-16 23:35
@jacobbloy It wouldn't take much to have this ported. I know there are a few people talking about it but no one that has actually done any work yet.

**Comment by kevinlynn** [comment] 2017-01-18 03:51
Has anyone noted how to get the turnigy evolution into DFU mode? The i6s had pads you could jumper but the mt6 doesn't. MT6 also has a set of holes labeled H1 with a test pad that is looks to be labeled UPDATA that I haven't seen in the original board.

It looks like the BOOT0 pin (pin 94) no longer has those traces going to pad and would need to be jumped on the resistor pads. Has anyone done this?

**Comment by andymac4182** [comment] 2017-01-18 03:59
@kevinlynn I believe its the same as the i6s according to an email I received from @fishpepper.

**Comment by kevinlynn** [comment] 2017-01-18 04:19
The i6s has a resistor on R59 just like the mt6 has. The only difference appears to be the pads (R60) on the i6s making it easier to jumper. I was really just asking because it would be nice if someone had traced it and found the pads elsewhere. I'm in the process of breaking out the pins to make it easy to work on this while the case is assembled and I'll admit that soldering onto smd components always makes me nervous. :)

**Comment by fishpepper** [comment] 2017-01-18 07:52
Right, R59 is the same. One side of R59 goes to gnd, the other one goes to the boot pin. Make sure to pull that one high (3.3V).

**Comment by DaveP2017** [comment] 2017-01-18 12:05
Sorry to be going off of the original topic, but ...

@kevinlynn the smaller smd sizes always used to make me nervous until I got a roll of kapton tape and masked everything within a 'large' radius

**Comment by kevinlynn** [comment] 2017-01-18 14:47
@fishpepper I'm confused, if I'm jumping R59 (BOOT0) with ground, if I pull 3.3v on the side of R59 that goes to boot0 then wont that cause a short?

Doesn't BOOT0 get 3.3v from powering up the radio once it's jumped?

@DaveP2017 - Thanks for the tip on the kapton tape. Don't you find it's hell to remove after you're done soldering?

**Comment by kevinlynn** [comment] 2017-01-18 15:51
I think I get it. The stm32f072 discovery board has boot0 being enabled by jumpering between P2.5 (vdd) and P2.6 (boot0). So it's not a jumper across the resistor but from the boot0 to vdd.

**Comment by DaveP2017** [comment] 2017-01-18 16:20
@kevinlynn 

The kapton peels away just fine if you don't hammer it onto the pcb, lol

> but from the boot0 to vdd.

yes... and in the order of 3v ish ( section 4.7 in the st.com manual)

**Comment by kevinlynn** [comment] 2017-01-19 17:22
Pinout of J4 on MT6:
O  |   O   |  O  |  O  |  O
--+-----+----+---+---
3  |    G   |  S  |  S  |  N
v  |    N   |  W | W  |  R
3  |    D   |  D  | C  |  S
    |          |   I   | L  |  T
    |          |  O  | K  |

It doesn't display well for that.. so let me try it sideways. :)
___________
o - 3v3     |
o - gnd     |
o - swdio |
o - swclk  |
o - nrst     |
___________|

This seems to be what I'm getting when I'm tracing wires. I'll test the 3.3v once I power it back up and see if that's legit.

**Comment by kevinlynn** [comment] 2017-01-19 23:44
[mt6-original-firmware.bin.zip](https://github.com/fishpepper/OpenGround/files/718056/mt6-original-firmware.bin.zip)

I'm connected to it and have pulled the original firmware. I'm putting it here just to be sure it doesn't get lost. :)

**Comment by jacobbloy** [comment] 2017-01-20 00:31
Is the firmware you pulled off of the evolution?

**Comment by kevinlynn** [comment] 2017-01-20 01:33
Yeah. It's the original firmware so it can't get lost.

**Comment by jacobbloy** [comment] 2017-01-20 02:46
Good idea, so your working on changing the ADC mapping for the evolution? I was planning on doing the same this week if I found time.

**Comment by kevinlynn** [comment] 2017-01-20 02:50
I think I'll upload the original firmware to a google drive instead. I'll be honest and say that I don't know if it's copyrighted and what the ramifications of putting it here are. Certainly you can't use it without an MT6 but I suppose they could still flip out or something.

If someone needs the original firmware then send me a message.

**Comment by andymac4182** [comment] 2017-01-23 22:34
http://fishpepper.de/2017/01/23/openground-part-12-turnigy-evolution-io-mapping/ 👍

**Comment by fishpepper** [comment] 2017-01-31 06:24
The latest master code works on Evolution. See src/config.c on how to enable autodetection on Evolution (a simple pulldown resistor is enough).

**Comment by andymac4182** [comment] 2017-01-31 06:31
@fishpepper Thanks!! sounds nice and simple.

**Comment by dovaskull** [comment] 2017-02-14 08:21
Hi guys, 

are you still working on this Project? I would wait for a tutorial for dummies to buy this transmitter, looks really nice but all my quads are FrSky.

Great advances @fishpepper

**Comment by rav-rav** [comment] 2017-02-14 11:37
I'd love to try it and work on it, but it is constantly on backorder at hobbyking. Is there some other store selling this transmitter?

**Comment by jacobbloy** [comment] 2017-02-14 12:43
Mode 1 radios are usually avalible, it is a simple swap over to mode 2, just look on YouTube if that helps

**Comment by keiser1080** [comment] 2017-02-14 18:19
I think but I AM not sure,  it's the same
http://m.banggood.com/fr/search/fs-i6s.html

**Comment by rav-rav** [comment] 2017-02-14 18:41
Thanks for the link, but I'm looking for the evolution, not i6s.

**Comment by totterfree** [comment] 2017-02-14 18:44
Two questions. 1. I can flash the current build, but will I actually be able to bind to frsky RXs at this point? 2. Is it possible to backup/revert to original firmware if I have problems?

**Comment by keiser1080** [comment] 2017-02-14 19:06
Indeed the evolution is a better radio following multiple reviews.
It's possible to use the multimodule 4in1 with this firmware + the
evolution ?

Le 14 févr. 2017 7:44 PM, "Timothy Ichiyasu" <notifications@github.com> a
écrit :

**Comment by fishpepper** [comment] 2017-02-14 20:48
The current build can bind. When you build the sources a txid and hoptable is generated and stored locally (src/hoptable.h) and in the hex file. You can also use the clone function to copy your other transmitter (no rebinding when you use multiple tx necessary).
UI navigation is done by the touchscreen (left/right corner to toggle screens). 4in1 module is not supported right now.

**Comment by keiser1080** [comment] 2017-02-14 22:27
Thanks for your wifi fishpepper!
"4in1 module is not supported right now."
It mean it may be supported in the futur 😀

Le 14 févr. 2017 9:48 PM, "fishpepper" <notifications@github.com> a écrit :

The current build can bind. When you build the sources a txid and hoptable
is generated and stored locally (src/hoptable.h) and in the hex file. You
can also use the clone function to copy your other transmitter (no
rebinding when you use multiple tx necessary).
UI navigation is done by the touchscreen (left/right corner to toggle
screens). 4in1 module is not supported right now.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/fishpepper/OpenGround/issues/1#issuecomment-279831219>,
or mute the thread

**Comment by jacobbloy** [comment] 2017-02-15 01:51
Support the porting of OpenTx to the turnigy evolution and I6s.
http://www.gofundme.com/3dudryg﻿

I have already emailed Fishpepper and if he is willing to do some payed work i can send some of the risen money his pay to get things like multi module support working and get usb joystick support working again for simulations work.

**Comment by kevinlynn** [comment] 2017-02-15 21:28
Fishpepper - do you have any coding standards  you want us to keep to in
order for us to submit changes for a7105 support?

I should be having some time for it next week and figure I'll see about
using some of the deviation stuff to make it easier...

**Comment by fishpepper** [comment] 2017-02-15 21:36
Just make sure it passes the automatic stylecheck (or do make stylecheck) :)

**Comment by rav-rav** [comment] 2017-02-26 14:08
My evolution finally arrived.
It has a 8MHz oscillator installed, not 12MHz, so CRYSTAL_FREQ / HSE_VALUE should be adjusted accordingly.

**Comment by fishpepper** [comment] 2017-02-26 15:04
You are right. The i6s also has an 8Mhz quartz. I need to investigate why this is working correctly with the 12.000000 value in the makefile. All timings are correct (9ms frame time for example). Maybe i messed up the sys clock initializing somehow so that it assumes 8mhz input. I will have to take a close look.

At least it is good to know that both use the same crystal ;)

Created a new issue #4 for this

**Comment by FAHQ13** [comment] 2017-03-31 03:46
Is the evo able to bind with frsky? Now that is. If so what do I have to do to make it work on my quads. I have a torretto 130 and the only receiver that fits is the furious fpv micro however it's frsky and I have a turnigy evolution and I love it but hate the frsky fsky flsky difference any help would be greatly appreciated

**Comment by MrSatoV** [comment] 2017-04-07 01:45
Just let me say, no matter the outcome, THANK YOU for your work on this guys.  Gives me hope where there was only frustration.  I love the TX but the RX options are irritatingly poor.  I like the X6B RX, but it's too big.  I actually already have on the way a Taranis Q X7 and some XM+ receivers - mostly just so I could use those receivers.  But I'd gladly sell off the Q X7 if you guys get this going as there's no way I'll like using it better than the Evo.  
Cheers!

**Comment by lunohod** [comment] 2017-04-27 01:47
I've just got a turnigy evo and waiting for the cc2500 to arrive. Do you have to remove the mainboard before replacing the rf module because of the screen on the other side?

**Comment by rav-rav** [comment] 2017-04-27 08:34
No need to remove it. Just open up the remote and you can get right to it.

**Comment by jacobbloy** [comment] 2017-04-27 08:59
Be carefully! Cont want to belt the crapy plastic wires and case. If using hot air remove the board or have a reflow temp control. If using solder wick then you can leave it in.

**Comment by lunohod** [comment] 2017-04-27 10:56
Thank you, guys! I'm going to use the solder wick. Just want to be sure not to ruin the display.

BTW, what is the best way to flash the fw updates without reopening the case each time? Can the OpenGround trigger the dfu mode? Or is it better to lead out the swd pins with a cable?

**Comment by totterfree** [comment] 2017-04-27 16:16
Is there any way we could get someone to describe, in detail, the steps for building/flashing this firmware? I'd like to make a video tutorial for other noobs if I can get this figured out for myself. Thanks in advance!

**Comment by lunohod** [comment] 2017-04-27 18:58
It's already described here: http://fishpepper.de/projects/openground/

Install the cross compiler:
`sudo apt-get install gcc-arm-none-eabi`

Download and build:
`git clone https://github.com/fishpepper/OpenGround.git && cd OpenGround`
`make`

Flash with st-link (http://fishpepper.de/2016/09/16/installing-using-st-link-v2-to-flash-stm32-on-linux/)
`make flash`
or using the DFU mode via USB (http://fishpepper.de/2016/09/16/openground-part-3-swd-st-link-debugger/)
`make dfu`

**Comment by ameeuw** [comment] 2017-04-29 19:18
Did anybody find out which pins the LEDs for the gimbals are on? Would love to have them light up on my Evolution when I use OpenGround.

**Comment by Adekamer** [comment] 2017-05-03 07:47
@kevinlynn , i brick my evolution 
i unsuccessful upgrade firmware
how i can receive  original firmware ?
how turn on evolution ?

**Comment by laurynas-karvelis** [comment] 2017-05-06 07:58
Someone else needs to do a backup of original firmware and send you the file somehow for you to try to restore it back.

**Comment by lunohod** [comment] 2017-05-06 20:28
@Adekamer here is my dump of the stock firmware: https://drive.google.com/file/d/0B0MGyLvt7DYTUTRELXZELW10Wms/view?usp=sharing

@ameeuw PA9 and PA10

**Comment by Adekamer** [comment] 2017-05-06 20:33
Thank you!

**Comment by jacobbloy** [comment] 2017-05-07 08:29
Are you sure that you didn't forget to do the pull-up resistor so the firmware can detect that it is an evolution? Otherwise it will just default to i6s which has different ADC and could stop your ratio powering on. Especially as the i6s has 2 power buttons.

**Comment by Adekamer** [comment] 2017-05-07 08:31
where is must be pull-ap resistor ?
1kOm enought ?
Thank.

**Comment by jacobbloy** [comment] 2017-05-07 08:43
Pin 10

**Comment by lunohod** [comment] 2017-05-07 08:54
It boots up fine without the pull-up resistor. If there is no gui, just flip the right switch :)

**Comment by lunohod** [comment] 2017-05-07 08:58
Btw, shouldn't it be a pull-down?
`// tgy evolution has a pulldown on RF0 (=PE.10)`

**Comment by jacobbloy** [comment] 2017-05-07 09:24
Haha yes sir

**Comment by jacobbloy** [comment] 2017-05-07 09:32
Soo to know about the right switch.
I was going to try and make a hex file that can be used with the GUI st-link software. Or make a was to install openground from the original flysky bootloader mode. So no need to use and st-link.

**Comment by lunohod** [comment] 2017-05-07 10:35
Well, it's the middle switch with the pull-down resistor installed.

I just hovered my Q85 with the turnigy evo and it is working! There are just some issues. OpenGround seems to use AETR, but all my betaflight copters are set to TAER. The switches are all inverted compared to my Taranis.

**Comment by jacobbloy** [comment] 2017-05-07 12:07
Can some one els please test this .hex file with an stink? you can use stink utilities on windows.

https://drive.google.com/open?id=0Bym9XrdeViekQXJ6dE8yZUdKYVU

**Comment by jacobbloy** [comment] 2017-05-07 14:19
![img_5161](https://cloud.githubusercontent.com/assets/7373557/25781915/3f33b690-337f-11e7-844e-65a785f80200.JPG)
confirmed .hex and i would say .bin works via st-link utility via windows. i could not get the .hex or .bin to work via DFU using a DFU gui.

ST-link utility can also be used to restore your firmware via a .bin (tested)

The image confirms what the screen will show if loaded with out a CC2500 installed. if your in Australia i have spare CC2500 adapters.

**Comment by jacobbloy** [comment] 2017-05-07 15:20
![img_7624](https://cloud.githubusercontent.com/assets/7373557/25782345/59af78b6-3388-11e7-9d63-78165149032c.JPG)

**Comment by lunohod** [comment] 2017-05-07 15:28
There was no place to fit both module and adapter board. I had to use wires instead.
![img_20170507_115719](https://cloud.githubusercontent.com/assets/16175/25782390/8b997d60-334a-11e7-8473-56bdcd0dfdc1.jpg)

**Comment by lunohod** [comment] 2017-05-07 15:43
I flashed my evo via DFU without any issues. And once the OpenGround is flashed you can trigger the DFU mode without soldering the boot pin.

**Comment by andresodio** [comment] 2017-05-07 17:35
Is soldering that blue board onto the Evolution a must for flying with
FrSky receivers? Or is there a way to use the stock Evolution HW with them?

Thanks,

Andrés

On May 7, 2017 09:28, "lunohod" <notifications@github.com> wrote:

There was no place to fit both modules and adapter board. I had to use
wires instead.
[image: img_20170507_115719]
<https://cloud.githubusercontent.com/assets/16175/25782390/8b997d60-334a-11e7-8473-56bdcd0dfdc1.jpg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fishpepper/OpenGround/issues/1#issuecomment-299713677>,
or mute the thread

**Comment by lunohod** [comment] 2017-05-07 19:05
@andresodio I guess the stock module will only work with AFHDS 2A receivers.

**Comment by jacobbloy** [comment] 2017-05-07 23:29
Is that a 1kohm or 110ohm?

And what was stopping your adapter board from fitting?

Some one would have to add support for ADHDS 2A and to work with the original module. Or look at support for the multiprotocole module. I was looking into it before the port so I'm waiting until that branch gets merged to start again.

**Comment by lunohod** [comment] 2017-05-07 23:39
On May 8, 2017 1:29 AM, "jacob bloy" <notifications@github.com> wrote:

Is that a 1kohm or 110ohm?


1k

And what was stopping your adapter board from fitting?

The height of the stack. I ordered my adapter at OSH, it's 1.6mm. But even
without the adapter I had to apply some force to close the case.

**Comment by jacobbloy** [comment] 2017-05-08 00:51
My case melted because I used hot air with out taking the board out so mine fits lol. One of those time where you say I shouldn't do this but do it any way.

**Comment by jacobbloy** [comment] 2017-05-08 07:04
I have opencm3 branch installed and all of the switches do strange things like turn the controller off is this a debugging feature?

**Comment by ponnex** [comment] 2017-05-14 13:24
@lunohod is the uploaded .bin files from the stock firmware that came with evolution or are those from the march updated firmware? :D

**Comment by lunohod** [comment] 2017-05-14 13:27
It was the stock fw I got with my evo shipped two weeks ago

On May 14, 2017 3:24 PM, "Emmanuel Francis Ramos Jr." <
notifications@github.com> wrote:

@lunohod <https://github.com/lunohod> is the uploaded .bin files from the
stock firmware that came with evolution or are those from the march updated
firmware? :D

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/fishpepper/OpenGround/issues/1#issuecomment-301312859>,
or mute the thread

**Comment by IdefixRC** [comment] 2017-08-19 08:49
Hi guys,

just received my Evolution and the RF module.
Is there a list of what works or does not work yet with the evolution after openground conversion?

Thanks !

**Comment by lunohod** [comment] 2017-08-19 09:30
I'm working on D16 support for the X receivers. I'll push my changes in two
weeks.

**Comment by MrSatoV** [comment] 2017-08-19 09:41
SWEET!

Shawn Sato-Veillon
佐藤  ショーン

**Comment by IdefixRC** [comment] 2017-08-19 11:24
@jacobbloy : Just flashed the hex simply using the Betaflight configurator firmware flasher. After soldering the boot pad it showed up as DFU in the Betaflight configurator and flashing the hex as local firmware file worked flawlessly !! Thanks for providing the file 🥇 

-------------------------------
jacobbloy 
Can some one els please test this .hex file with an stink? you can use stink utilities on windows.https://drive.google.com/open?id=0Bym9XrdeViekQXJ6dE8yZUdKYVU
--

**Comment by andymac4182** [comment] 2017-08-20 02:01
Be cool to work towards an alternative firmware/hardware tx for FrSky. Similar to what the FU-RC guys are working on. Something controlled via a phone as a screen similar to the Mavic controller. Sounds like this is becoming a great firmware for the quad racing industry.

**Comment by IdefixRC** [comment] 2017-08-20 06:41
@fishpepper 
First of all: AWESOME work. Thanks a lot for putting the effort in (Eine super Leistung :-) )
After testing the hex from jacobblow above and finding out that it was based on his own fork which explained why I had so many issues. I compiled from the latest master and flashed the binary via DFU onto the evolution..

It boots up very quickly and all the menu's as well as the stick calibration work fine.
I have however issues getting it to talk to the receiver.

Bind mode: Put the RX into bind mode (2 solid LED's), as soon as I hit bind on the TX one RX led starts blinking as it should indicating that it receives the bind packets. However upon restart of both TX and RX, the RX simply blinks indicating no connection.

TX Clone: I tried that next. Put the Evolution in Clone TX mode, powered my taranis up and hit bind. The evolution started with the autocalibration etc and finished with "please switch off now".
After powering it back up the RX still could not connect (powering the taranis up makes it connect instantly to the taranis).

Any ideas on what I'm doing wrong? I assume that the TX module connections are fine given it can send and receive (at least looks like that from the tests above).

Thanks

**Comment by fishpepper** [comment] 2017-08-20 07:34
This sounds strange. Were you really close to the rx? Try it at a distance of 2m or more.
How does the hoptable look like? It should be printed on the debug console during boot (a list of some hex values).

Please use the opencm3 branch for further developments, this is going to be replace master soon
https://github.com/fishpepper/OpenGround/tree/opencm3

That one uses the open source stm3 library instead of the st one. I attached output files for the latest revision of then opencm3 branch to this post.



[openground_opencm3_4a57a5b6fb.zip](https://github.com/fishpepper/OpenGround/files/1236919/openground_opencm3_4a57a5b6fb.zip)

**Comment by IdefixRC** [comment] 2017-08-20 07:44
Thanks for the quick reply. Yes the RX was very close. Will try again with some distance between it and the TX. 

As for the opencm branch: is it stable enough for basic flying? Or should i try to get it working with the master first? 

Thanks

**Comment by IdefixRC** [comment] 2017-08-20 07:56
Tested with the RX a few meters away. Same behavior unfortunately.
Hoptable: is there a possibility to scroll up in the debug screen? It runs through to fast and the only hex values I see on the final screen are those behind: calib fscal1: 1B 20 24 1B 20 24 1B 20 24

Here is a Screenshot of the debug screen: https://goo.gl/photos/nyoLT5hk2WfeTKXx7

**Comment by hobojoe720** [comment] 2017-08-23 10:18
Hey guys, read all this a while ago and forgot about it.
I see from the pics that there is a module to replace the built in FlySky one. is it possible to use the Multi Protocol module in that case? Or is that still a no go without going down the route of having the module external with a receiver feeding it signals?

Also, if I flash the HEX to my Evo, without changing the TX module, I assume I can still bind to all my existing flySky receivers?

**Comment by Patrick-Wilson** [comment] 2017-08-24 12:48
Really interesting! I'll be testing this out soon on my Evolution.. Props to @fishpepper, great idea..

**Comment by lunohod** [comment] 2017-08-24 13:18
No, it wont't work. The OpenGround can only talk to the cc2500 module.

On Aug 23, 2017 12:18, "hobojoe720" <notifications@github.com> wrote:

Hey guys, read all this a while ago and forgot about it.
I see from the pics that there is a module to replace the built in FlySky
one. is it possible to use the Multi Protocol module in that case? Or is
that still a no go without going down the route of having the module
external with a receiver feeding it signals?

Also, if I flash the HEX to my Evo, without changing the TX module, I
assume I can still bind to all my existing flySky receivers?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fishpepper/OpenGround/issues/1#issuecomment-324286340>,
or mute the thread

**Comment by IdefixRC** [comment] 2017-08-24 13:26
@fishpepper 
Was not able to run further tests during the week but will look into it again on the weekend.
Did you have time to look at the below? Any idea?

Tested with the RX a few meters away. Same behavior unfortunately.
Hoptable: is there a possibility to scroll up in the debug screen? It runs through to fast and the only hex values I see on the final screen are those behind: calib fscal1: 1B 20 24 1B 20 24 1B 20 24

Here is a Screenshot of the debug screen: https://goo.gl/photos/nyoLT5hk2WfeTKXx7

**Comment by fishpepper** [comment] 2017-08-24 14:06
Unfortunately you can not scroll up in this screen. 
You could place a while(1); after the debug print with the hop table for now.

**Comment by rav-rav** [comment] 2017-08-24 18:08
@hobojoe720 
@lunohod 
I did some initial work on porting code from the multiprotocol project here: https://github.com/rav-rav/OpenGround/commits/opencm3
![4in1](https://user-images.githubusercontent.com/17462561/29681448-fa3e6272-8907-11e7-83bf-399a76beffb2.jpg)

**Comment by jacobbloy** [comment] 2017-08-25 00:39
@rav-rav
It looks like you have intergrated the module with out a second mcu, is this correct?
It would be good if you could bring your branch inline with @fishpepper so this hid joystick integration are also added.

**Comment by rav-rav** [comment] 2017-08-25 07:10
@jacobbloy 
Yes, this module does not have a second mcu and even fits into the enclosing. Unfortunately I didn't have much time to work further on it.

Here's an older version which does work using a serial connection to the module with mcu: https://github.com/rav-rav/OpenGround/commits/multi4in1serial

**Comment by shadow974** [comment] 2017-08-27 09:54
Just flashed the latest Opencm3-Edition to my turnigy evolution. The Hardware is detected correctly as Turnigy Evolution. The AD-Readings seems to be inverted. TX-Clone does nothing for me (stays in Setup menu)

Edit: On the master-branch the menu works and the TX-ID is synched.

**Comment by shadow974** [comment] 2017-08-28 14:19
Ok, just found the part in the sources. The complete clone-process is commented out an the user ist thrown back to the main settings menu. But why?

 I removed the comment-tag, compiled it without problems and it seems to run correctly. Have to try at home with my Taranis.

**Comment by shadow974** [comment] 2017-08-28 18:18
Ok, tested with my taranis and it never gets out of the "preparing autotune" part, so no luck with that. I tracked it down to the function frsky_autotune_do, in step "case (1)". It seems he never receives a valid frame?

The inverted AD-Values are because of my Stick Mode 1 Version (where you swap and rotate the gimbals inside)

**Comment by Patrick-Wilson** [comment] 2017-08-29 07:57
@shadow974 I have a mode 1 version, the inverted AD-values can be corrected by unplugging the gimbals from their connecting pcb and swapping the ribbon cables over after the swap and rotate.. worked for me.. 

Problem I am having, I suspect, is a dead CC2500 module? problems I am seeing are complete freeze / lockup when trying to bind or clone (have to pull the batteries out to power off) and I am getting no signal power level output reading in the UI.. Anyone had / corrected this?

**Comment by IdefixRC** [comment] 2017-08-29 11:31
@fishpepper 
Thanks for the reply. I went through the code but could not find the obvious place for the hoptable debug line. Assume it is one of the debug messages in debug.h?
Could you point me at the right file?

Thanks

--------------------
Unfortunately you can not scroll up in this screen.
You could place a while(1); after the debug print with the hop table for now.

**Comment by fishpepper** [comment] 2017-08-29 19:22
@all:
I just fixed the non-working clone tx and some other bugs that made the opencm3 branch non-working.
It's working again. Thanks for pointing out the issues! I merged the opencm3 into master, so now the code to use is the master branch again :)
I will close this issue now (tgy evolution is supported). Please re-open separate issues for any occuring problems. It's way easier to keep track what's going on!

**Closed as completed by fishpepper** 2017-08-29 19:22 UTC

**Comment by John-Titor** [comment] 2018-01-30 04:42
@lunohod Did you (or someone else) finish the D16 work? Your repo looks like you were still working on it...

**Comment by lunohod** [comment] 2018-01-30 08:03
@John-Titor Well, it's still work in progress, but I got D16 working. It was a fast and dirty hack to make it work right before my vacations back in summer. I just replaced D8 with D16, no telemetry, no binding. Right now I'm working on making both D8 and D16 work, gimme a week and I'll upload something working.

**Comment by John-Titor** [comment] 2018-01-30 17:36
Thanks! I have to wait for my cc2500 module to show up, so no rush.

**Comment by lunohod** [comment] 2018-02-02 15:57
@John-Titor https://github.com/lunohod/OpenGround/commits/new_features
